steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - client/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/dnd-booker-client:${_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/dnd-booker-client:${_TAG}

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - server/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/dnd-booker-server:${_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/dnd-booker-server:${_TAG}

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - worker/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/dnd-booker-worker:${_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/dnd-booker-worker:${_TAG}

substitutions:
  _REGION: us-west4
  _REPO: dnd-booker
  _TAG: latest

options:
  logging: CLOUD_LOGGING_ONLY
